[build]
  command = "cd frontend && yarn build"
  publish = "frontend/build"

[build.environment]
  NODE_VERSION = "18"
  YARN_VERSION = "1.22.22"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
