"""Curated emotion map for the 13x13 feeling grid.
X axis: -6 (unpleasant) to +6 (pleasant)
Y axis: -6 (low energy) to +6 (high energy)

Keys are "x,y" strings. Entries marked TODO are placeholders — edit them.
"""

CURATED_EMOTIONS = {
    # ---- y = +6 (high energy) ----
    "-6,6": {"name": "Outraged", "description": "This should not be happening. Your whole body agrees, loudly."},
    "-5,6": {"name": "TODO (-5,+6)", "description": "TODO: add description for coordinate (-5, +6)."},
    "-4,6": {"name": "TODO (-4,+6)", "description": "TODO: add description for coordinate (-4, +6)."},
    "-3,6": {"name": "Anxious", "description": "A restless drum in the chest — thoughts sprint ahead to every possible way it could go wrong."},
    "-2,6": {"name": "TODO (-2,+6)", "description": "TODO: add description for coordinate (-2, +6)."},
    "-1,6": {"name": "TODO (-1,+6)", "description": "TODO: add description for coordinate (-1, +6)."},
    "0,6": {"name": "TODO (+0,+6)", "description": "TODO: add description for coordinate (+0, +6)."},
    "1,6": {"name": "TODO (+1,+6)", "description": "TODO: add description for coordinate (+1, +6)."},
    "2,6": {"name": "TODO (+2,+6)", "description": "TODO: add description for coordinate (+2, +6)."},
    "3,6": {"name": "Excited", "description": "A bright buzz in the chest — something good is coming and you can barely sit still."},
    "4,6": {"name": "Energized", "description": "A humming readiness — you want to move, do, build, go."},
    "5,6": {"name": "TODO (+5,+6)", "description": "TODO: add description for coordinate (+5, +6)."},
    "6,6": {"name": "Exhilarated", "description": "Wind-in-hair, heart-hammering aliveness — you feel powerfully awake and free."},

    # ---- y = +5 (high energy) ----
    "-6,5": {"name": "TODO (-6,+5)", "description": "TODO: add description for coordinate (-6, +5)."},
    "-5,5": {"name": "Panicked", "description": "The world narrows to a bright pinpoint. Breath shortens, and every option feels like danger."},
    "-4,5": {"name": "TODO (-4,+5)", "description": "TODO: add description for coordinate (-4, +5)."},
    "-3,5": {"name": "TODO (-3,+5)", "description": "TODO: add description for coordinate (-3, +5)."},
    "-2,5": {"name": "TODO (-2,+5)", "description": "TODO: add description for coordinate (-2, +5)."},
    "-1,5": {"name": "Nervous", "description": "A fluttery undercurrent. You're preparing for something that hasn't happened yet."},
    "0,5": {"name": "Aroused", "description": "Sharply awake — your nervous system is pointing at something intently."},
    "1,5": {"name": "Amused", "description": "A crinkle at the corner of the eye — something delightful just tickled you sideways."},
    "2,5": {"name": "TODO (+2,+5)", "description": "TODO: add description for coordinate (+2, +5)."},
    "3,5": {"name": "TODO (+3,+5)", "description": "TODO: add description for coordinate (+3, +5)."},
    "4,5": {"name": "TODO (+4,+5)", "description": "TODO: add description for coordinate (+4, +5)."},
    "5,5": {"name": "Elated", "description": "Lifted, glowing, half-floating. The world momentarily feels like it's on your side."},
    "6,5": {"name": "TODO (+6,+5)", "description": "TODO: add description for coordinate (+6, +5)."},

    # ---- y = +4 (high energy) ----
    "-6,4": {"name": "TODO (-6,+4)", "description": "TODO: add description for coordinate (-6, +4)."},
    "-5,4": {"name": "TODO (-5,+4)", "description": "TODO: add description for coordinate (-5, +4)."},
    "-4,4": {"name": "Overwhelmed", "description": "Too much, too fast. Your mind is trying to hold ten glasses of water at once."},
    "-3,4": {"name": "TODO (-3,+4)", "description": "TODO: add description for coordinate (-3, +4)."},
    "-2,4": {"name": "Frustrated", "description": "The thing keeps not working and something inside you is starting to push back hard."},
    "-1,4": {"name": "TODO (-1,+4)", "description": "TODO: add description for coordinate (-1, +4)."},
    "0,4": {"name": "TODO (+0,+4)", "description": "TODO: add description for coordinate (+0, +4)."},
    "1,4": {"name": "TODO (+1,+4)", "description": "TODO: add description for coordinate (+1, +4)."},
    "2,4": {"name": "Playful", "description": "A mischievous lightness — you want to poke, tease, and make everyone laugh with you."},
    "3,4": {"name": "TODO (+3,+4)", "description": "TODO: add description for coordinate (+3, +4)."},
    "4,4": {"name": "Inspired", "description": "A quick current of aliveness — you want to make something before the feeling fades."},
    "5,4": {"name": "TODO (+5,+4)", "description": "TODO: add description for coordinate (+5, +4)."},
    "6,4": {"name": "TODO (+6,+4)", "description": "TODO: add description for coordinate (+6, +4)."},

    # ---- y = +3 (high energy) ----
    "-6,3": {"name": "Angry", "description": "Heat behind the eyes, teeth set. A line has been crossed and you feel it in your body."},
    "-5,3": {"name": "Agitated", "description": "You can't sit still and you don't quite know why — everything grates."},
    "-4,3": {"name": "TODO (-4,+3)", "description": "TODO: add description for coordinate (-4, +3)."},
    "-3,3": {"name": "Tense", "description": "Shoulders up, jaw tight, watching for the next thing that might go wrong."},
    "-2,3": {"name": "TODO (-2,+3)", "description": "TODO: add description for coordinate (-2, +3)."},
    "-1,3": {"name": "TODO (-1,+3)", "description": "TODO: add description for coordinate (-1, +3)."},
    "0,3": {"name": "Attentive", "description": "You are here, watching, listening — the world has your full presence."},
    "1,3": {"name": "TODO (+1,+3)", "description": "TODO: add description for coordinate (+1, +3)."},
    "2,3": {"name": "TODO (+2,+3)", "description": "TODO: add description for coordinate (+2, +3)."},
    "3,3": {"name": "Cheerful", "description": "A steady sunny mood you carry into rooms without meaning to."},
    "4,3": {"name": "TODO (+4,+3)", "description": "TODO: add description for coordinate (+4, +3)."},
    "5,3": {"name": "Delighted", "description": "That small surprised laugh you make when the world does something charming."},
    "6,3": {"name": "Joyful", "description": "Warm, uncomplicated happiness spreading outward from somewhere behind your sternum."},

    # ---- y = +2 (high energy) ----
    "-6,2": {"name": "TODO (-6,+2)", "description": "TODO: add description for coordinate (-6, +2)."},
    "-5,2": {"name": "TODO (-5,+2)", "description": "TODO: add description for coordinate (-5, +2)."},
    "-4,2": {"name": "Irritated", "description": "A grain of sand under the eyelid of the day — small, but you can't stop noticing it."},
    "-3,2": {"name": "TODO (-3,+2)", "description": "TODO: add description for coordinate (-3, +2)."},
    "-2,2": {"name": "Worried", "description": "A quiet loop in the background asking what if, what if, what if."},
    "-1,2": {"name": "TODO (-1,+2)", "description": "TODO: add description for coordinate (-1, +2)."},
    "0,2": {"name": "TODO (+0,+2)", "description": "TODO: add description for coordinate (+0, +2)."},
    "1,2": {"name": "TODO (+1,+2)", "description": "TODO: add description for coordinate (+1, +2)."},
    "2,2": {"name": "Interested", "description": "Leaning in — this has your curiosity and it's building."},
    "3,2": {"name": "TODO (+3,+2)", "description": "TODO: add description for coordinate (+3, +2)."},
    "4,2": {"name": "Enthusiastic", "description": "You're all-in. Ideas flow, energy pours forward, and doing feels effortless."},
    "5,2": {"name": "TODO (+5,+2)", "description": "TODO: add description for coordinate (+5, +2)."},
    "6,2": {"name": "TODO (+6,+2)", "description": "TODO: add description for coordinate (+6, +2)."},

    # ---- y = +1 (high energy) ----
    "-6,1": {"name": "TODO (-6,+1)", "description": "TODO: add description for coordinate (-6, +1)."},
    "-5,1": {"name": "Resentful", "description": "A slow burn about something unfair — you keep replaying it and it keeps stinging."},
    "-4,1": {"name": "TODO (-4,+1)", "description": "TODO: add description for coordinate (-4, +1)."},
    "-3,1": {"name": "TODO (-3,+1)", "description": "TODO: add description for coordinate (-3, +1)."},
    "-2,1": {"name": "TODO (-2,+1)", "description": "TODO: add description for coordinate (-2, +1)."},
    "-1,1": {"name": "TODO (-1,+1)", "description": "TODO: add description for coordinate (-1, +1)."},
    "0,1": {"name": "TODO (+0,+1)", "description": "TODO: add description for coordinate (+0, +1)."},
    "1,1": {"name": "Pleased", "description": "A small quiet yes. Something worked out and you noticed it."},
    "2,1": {"name": "TODO (+2,+1)", "description": "TODO: add description for coordinate (+2, +1)."},
    "3,1": {"name": "TODO (+3,+1)", "description": "TODO: add description for coordinate (+3, +1)."},
    "4,1": {"name": "TODO (+4,+1)", "description": "TODO: add description for coordinate (+4, +1)."},
    "5,1": {"name": "Optimistic", "description": "You can see the shape of a good outcome, and you trust it enough to keep going."},
    "6,1": {"name": "Confident", "description": "Squared shoulders and a quiet certainty. You know what you can do."},

    # ---- y = +0 (neutral energy) ----
    "-6,0": {"name": "Bitter", "description": "A metallic aftertaste from something that didn't heal cleanly."},
    "-5,0": {"name": "TODO (-5,+0)", "description": "TODO: add description for coordinate (-5, +0)."},
    "-4,0": {"name": "TODO (-4,+0)", "description": "TODO: add description for coordinate (-4, +0)."},
    "-3,0": {"name": "Uneasy", "description": "Something is off. You can't name it, but you can feel it in your posture."},
    "-2,0": {"name": "TODO (-2,+0)", "description": "TODO: add description for coordinate (-2, +0)."},
    "-1,0": {"name": "TODO (-1,+0)", "description": "TODO: add description for coordinate (-1, +0)."},
    "0,0": {"name": "Neutral", "description": "The quiet middle — neither drawn toward nor away from anything in particular."},
    "1,0": {"name": "TODO (+1,+0)", "description": "TODO: add description for coordinate (+1, +0)."},
    "2,0": {"name": "TODO (+2,+0)", "description": "TODO: add description for coordinate (+2, +0)."},
    "3,0": {"name": "Okay", "description": "A stable, unremarkable good — the kind you don't notice unless someone asks."},
    "4,0": {"name": "TODO (+4,+0)", "description": "TODO: add description for coordinate (+4, +0)."},
    "5,0": {"name": "TODO (+5,+0)", "description": "TODO: add description for coordinate (+5, +0)."},
    "6,0": {"name": "TODO (+6,+0)", "description": "TODO: add description for coordinate (+6, +0)."},

    # ---- y = -1 (low energy) ----
    "-6,-1": {"name": "TODO (-6,-1)", "description": "TODO: add description for coordinate (-6, -1)."},
    "-5,-1": {"name": "Hurt", "description": "Something soft in you was bruised, and it's still tender to touch."},
    "-4,-1": {"name": "TODO (-4,-1)", "description": "TODO: add description for coordinate (-4, -1)."},
    "-3,-1": {"name": "Melancholy", "description": "A soft-blue mood — not painful, but ache-adjacent and hard to shake."},
    "-2,-1": {"name": "TODO (-2,-1)", "description": "TODO: add description for coordinate (-2, -1)."},
    "-1,-1": {"name": "TODO (-1,-1)", "description": "TODO: add description for coordinate (-1, -1)."},
    "0,-1": {"name": "TODO (+0,-1)", "description": "TODO: add description for coordinate (+0, -1)."},
    "1,-1": {"name": "TODO (+1,-1)", "description": "TODO: add description for coordinate (+1, -1)."},
    "2,-1": {"name": "Grateful", "description": "A warm noticing of what is good. You don't want to move past it too quickly."},
    "3,-1": {"name": "Warm", "description": "A soft affection toward the moment and whoever is in it with you."},
    "4,-1": {"name": "TODO (+4,-1)", "description": "TODO: add description for coordinate (+4, -1)."},
    "5,-1": {"name": "Satisfied", "description": "That warm nod inside — a thing you cared about is finally, quietly done."},
    "6,-1": {"name": "TODO (+6,-1)", "description": "TODO: add description for coordinate (+6, -1)."},

    # ---- y = -2 (low energy) ----
    "-6,-2": {"name": "TODO (-6,-2)", "description": "TODO: add description for coordinate (-6, -2)."},
    "-5,-2": {"name": "TODO (-5,-2)", "description": "TODO: add description for coordinate (-5, -2)."},
    "-4,-2": {"name": "Discouraged", "description": "The path forward looks longer than your legs feel. You keep sighing without noticing."},
    "-3,-2": {"name": "TODO (-3,-2)", "description": "TODO: add description for coordinate (-3, -2)."},
    "-2,-2": {"name": "TODO (-2,-2)", "description": "TODO: add description for coordinate (-2, -2)."},
    "-1,-2": {"name": "Meh", "description": "A soft, indifferent shrug. Nothing calls, nothing complains."},
    "0,-2": {"name": "TODO (+0,-2)", "description": "TODO: add description for coordinate (+0, -2)."},
    "1,-2": {"name": "At Ease", "description": "Comfortable in your own skin, breathing on its own accord."},
    "2,-2": {"name": "TODO (+2,-2)", "description": "TODO: add description for coordinate (+2, -2)."},
    "3,-2": {"name": "TODO (+3,-2)", "description": "TODO: add description for coordinate (+3, -2)."},
    "4,-2": {"name": "Comfortable", "description": "Snug in your own life for a moment. Everything fits where it is."},
    "5,-2": {"name": "TODO (+5,-2)", "description": "TODO: add description for coordinate (+5, -2)."},
    "6,-2": {"name": "TODO (+6,-2)", "description": "TODO: add description for coordinate (+6, -2)."},

    # ---- y = -3 (low energy) ----
    "-6,-3": {"name": "Lonely", "description": "A room-shaped ache. Even in company, you feel like you're behind a pane of glass."},
    "-5,-3": {"name": "Rejected", "description": "A door closed you were standing at. You keep looking at the door."},
    "-4,-3": {"name": "TODO (-4,-3)", "description": "TODO: add description for coordinate (-4, -3)."},
    "-3,-3": {"name": "Down", "description": "Lower than baseline, lightly weighted. You'd rather stay small today."},
    "-2,-3": {"name": "TODO (-2,-3)", "description": "TODO: add description for coordinate (-2, -3)."},
    "-1,-3": {"name": "TODO (-1,-3)", "description": "TODO: add description for coordinate (-1, -3)."},
    "0,-3": {"name": "TODO (+0,-3)", "description": "TODO: add description for coordinate (+0, -3)."},
    "1,-3": {"name": "TODO (+1,-3)", "description": "TODO: add description for coordinate (+1, -3)."},
    "2,-3": {"name": "TODO (+2,-3)", "description": "TODO: add description for coordinate (+2, -3)."},
    "3,-3": {"name": "Mellow", "description": "Softened around the edges. Whatever song is playing feels like the right one."},
    "4,-3": {"name": "TODO (+4,-3)", "description": "TODO: add description for coordinate (+4, -3)."},
    "5,-3": {"name": "Loved", "description": "Held. Somewhere in the world, you matter to someone, and you can feel it."},
    "6,-3": {"name": "Calm", "description": "Even-keeled and settled. Whatever happens, you can meet it."},

    # ---- y = -4 (low energy) ----
    "-6,-4": {"name": "TODO (-6,-4)", "description": "TODO: add description for coordinate (-6, -4)."},
    "-5,-4": {"name": "TODO (-5,-4)", "description": "TODO: add description for coordinate (-5, -4)."},
    "-4,-4": {"name": "Weary", "description": "Not just tired — worn. Something has been carried for too long."},
    "-3,-4": {"name": "TODO (-3,-4)", "description": "TODO: add description for coordinate (-3, -4)."},
    "-2,-4": {"name": "Disappointed", "description": "You wanted it to be different, and now you're sitting with the difference."},
    "-1,-4": {"name": "TODO (-1,-4)", "description": "TODO: add description for coordinate (-1, -4)."},
    "0,-4": {"name": "Bored", "description": "Nothing is pulling at you and nothing has decided to be interesting yet."},
    "1,-4": {"name": "TODO (+1,-4)", "description": "TODO: add description for coordinate (+1, -4)."},
    "2,-4": {"name": "Relaxed", "description": "Shoulders down, breath long. You have permission to just exist right now."},
    "3,-4": {"name": "TODO (+3,-4)", "description": "TODO: add description for coordinate (+3, -4)."},
    "4,-4": {"name": "TODO (+4,-4)", "description": "TODO: add description for coordinate (+4, -4)."},
    "5,-4": {"name": "TODO (+5,-4)", "description": "TODO: add description for coordinate (+5, -4)."},
    "6,-4": {"name": "TODO (+6,-4)", "description": "TODO: add description for coordinate (+6, -4)."},

    # ---- y = -5 (low energy) ----
    "-6,-5": {"name": "TODO (-6,-5)", "description": "TODO: add description for coordinate (-6, -5)."},
    "-5,-5": {"name": "Miserable", "description": "Wrapped in gray. It's hard to remember what feeling okay was like."},
    "-4,-5": {"name": "TODO (-4,-5)", "description": "TODO: add description for coordinate (-4, -5)."},
    "-3,-5": {"name": "TODO (-3,-5)", "description": "TODO: add description for coordinate (-3, -5)."},
    "-2,-5": {"name": "TODO (-2,-5)", "description": "TODO: add description for coordinate (-2, -5)."},
    "-1,-5": {"name": "Gloomy", "description": "A low overcast mood — nothing terrible, just no sun coming through anywhere."},
    "0,-5": {"name": "TODO (+0,-5)", "description": "TODO: add description for coordinate (+0, -5)."},
    "1,-5": {"name": "Drowsy", "description": "A pleasant, warm heaviness pulling gently toward sleep."},
    "2,-5": {"name": "TODO (+2,-5)", "description": "TODO: add description for coordinate (+2, -5)."},
    "3,-5": {"name": "TODO (+3,-5)", "description": "TODO: add description for coordinate (+3, -5)."},
    "4,-5": {"name": "TODO (+4,-5)", "description": "TODO: add description for coordinate (+4, -5)."},
    "5,-5": {"name": "Tranquil", "description": "Still water. Your thoughts drift past without wanting anything from you."},
    "6,-5": {"name": "TODO (+6,-5)", "description": "TODO: add description for coordinate (+6, -5)."},

    # ---- y = -6 (low energy) ----
    "-6,-6": {"name": "Grief-stricken", "description": "A great weight has settled where a great presence used to be."},
    "-5,-6": {"name": "TODO (-5,-6)", "description": "TODO: add description for coordinate (-5, -6)."},
    "-4,-6": {"name": "TODO (-4,-6)", "description": "TODO: add description for coordinate (-4, -6)."},
    "-3,-6": {"name": "Sad", "description": "A heavy softness that pulls the edges of everything downward. Tears live close to the surface."},
    "-2,-6": {"name": "Sullen", "description": "Turned inward, low-simmering. You'd rather not be talked to right now."},
    "-1,-6": {"name": "TODO (-1,-6)", "description": "TODO: add description for coordinate (-1, -6)."},
    "0,-6": {"name": "Fatigued", "description": "The body is asking, then telling, then insisting on rest."},
    "1,-6": {"name": "TODO (+1,-6)", "description": "TODO: add description for coordinate (+1, -6)."},
    "2,-6": {"name": "TODO (+2,-6)", "description": "TODO: add description for coordinate (+2, -6)."},
    "3,-6": {"name": "Peaceful", "description": "A slow, unhurried okay-ness. Nothing tugs at you and you're grateful for it."},
    "4,-6": {"name": "TODO (+4,-6)", "description": "TODO: add description for coordinate (+4, -6)."},
    "5,-6": {"name": "TODO (+5,-6)", "description": "TODO: add description for coordinate (+5, -6)."},
    "6,-6": {"name": "Restful", "description": "Deeply at ease — the kind of rest that repairs quiet damage you didn't know was there."},

}
